name: Deployment react app on AWS S3
on:
  push:
    branches: [main]

env:
  BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
  AWS_REGION: "ap-northeast-2"
  REACT_APP_CAL_API_KEY: ${{secrets.REACT_APP_CAL_API_KEY}}
  REACT_APP_KAKAOMAP_KEY: ${{secrets.REACT_APP_KAKAOMAP_KEY}}
  REACT_APP_ACCOUNT_CLIENT_ID: ${{secrets.REACT_APP_ACCOUNT_CLIENT_ID}}
  REACT_APP_ACCOUNT_STATE: ${{secrets.REACT_APP_ACCOUNT_STATE}}

permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone this repository
        uses: actions/checkout@v4

      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.18.0"

      - name: Update npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies
        run: CI='false' npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{env.AWS_REGION}}

      - name: Copy build file to S3
        run: aws s3 sync ./build/ s3://${{env.BUCKET_NAME}}/
